# Created by react-native-pod
target 'MyFiziqExample' do
  # MyFiziq requires iOS 12.1 minimal (for CoreML 2). This is minimal AppStore accept now anyway
  platform :ios, '12.1'
  # We uncomment because we like dynamic frameworks witn working with swift projects
  use_frameworks!
  # Add new pods below this line
  pod 'RNMyFiziqSdk', :path => '../node_modules/react-native-my-fiziq-sdk/ios'
  pod 'MyFiziqSDK', :git => 'https://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/myfiziq-sdk-ios', :branch => '19.1.9'
  pod 'MyFiziqSDKBilling', :git => 'https://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/myfiziq-sdk-ios-billing', :branch => '19.1.9'
  pod 'MyFiziqSDKCommon', :git => 'https://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/myfiziq-sdk-common', :branch => '19.1.9'

  target 'MyFiziqExampleTests' do
    inherit! :search_paths
    # Pods for testing
    # Add new pods below this line
    pod 'RNMyFiziqSdk', :path => '../node_modules/react-native-my-fiziq-sdk/ios'
    pod 'MyFiziqSDK', :git => 'https://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/myfiziq-sdk-ios', :branch => '19.1.9'
    pod 'MyFiziqSDKBilling', :git => 'https://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/myfiziq-sdk-ios-billing', :branch => '19.1.9'
    pod 'MyFiziqSDKCommon', :git => 'https://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/myfiziq-sdk-common', :branch => '19.1.9'
  end
end
target 'MyFiziqExample-tvOS' do
  # MyFiziq requires iOS 12.1 minimal (for CoreML 2). This is minimal AppStore accept now anyway
  platform :ios, '12.1'
  # We uncomment because we like dynamic frameworks witn working with swift projects
  use_frameworks!
  target 'MyFiziqExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end